insert into CITIES (id, name, country) values (1, 'San Simon', 'Philippines');
insert into CITIES (id, name, country) values (2, 'Ekou', 'China');
insert into CITIES (id, name, country) values (3, 'Guinsadan', 'Philippines');
insert into CITIES (id, name, country) values (4, 'Malata', 'Indonesia');
insert into CITIES (id, name, country) values (5, 'Concepción de la Barranca', 'Honduras');
insert into CITIES (id, name, country) values (6, 'Lamarosa', 'Portugal');
insert into CITIES (id, name, country) values (7, 'Sam Roi Yot', 'Thailand');
insert into CITIES (id, name, country) values (8, 'São José do Rio Pardo', 'Brazil');
insert into CITIES (id, name, country) values (9, 'Shōbu', 'Japan');
insert into CITIES (id, name, country) values (10, 'Pleiku', 'Vietnam');
insert into CITIES (id, name, country) values (11, 'Briteiros Santa Leocádia', 'Portugal');
insert into CITIES (id, name, country) values (12, 'Meishan', 'China');
insert into CITIES (id, name, country) values (13, 'Hucun', 'China');
insert into CITIES (id, name, country) values (14, 'Sarakhs', 'Iran');
insert into CITIES (id, name, country) values (15, 'El Carmen', 'Colombia');
insert into CITIES (id, name, country) values (16, 'Capas', 'Philippines');
insert into CITIES (id, name, country) values (17, 'Al Başrah', 'Iraq');
insert into CITIES (id, name, country) values (18, 'Breu', 'Peru');
insert into CITIES (id, name, country) values (19, 'Cuito', 'Angola');
insert into CITIES (id, name, country) values (20, 'Ondoy', 'Philippines');
insert into CITIES (id, name, country) values (21, 'Likupang', 'Indonesia');
insert into CITIES (id, name, country) values (22, 'Fenghuang', 'China');
insert into CITIES (id, name, country) values (23, 'Poříčí nad Sázavou', 'Czech Republic');
insert into CITIES (id, name, country) values (24, 'Budaka', 'Uganda');
insert into CITIES (id, name, country) values (25, 'Patao', 'Philippines');
insert into CITIES (id, name, country) values (26, 'Qingshan', 'China');
insert into CITIES (id, name, country) values (27, 'Baisha', 'China');
insert into CITIES (id, name, country) values (28, 'Al Qadarif', 'Sudan');
insert into CITIES (id, name, country) values (29, 'Layog', 'Philippines');
insert into CITIES (id, name, country) values (30, 'Gongping', 'China');
insert into CITIES (id, name, country) values (31, 'Wodzierady', 'Poland');
insert into CITIES (id, name, country) values (32, 'Goryachevodskiy', 'Russia');
insert into CITIES (id, name, country) values (33, 'Xiuyu', 'China');
insert into CITIES (id, name, country) values (34, 'Donghai', 'China');
insert into CITIES (id, name, country) values (35, 'Mokopane', 'South Africa');
insert into CITIES (id, name, country) values (36, 'Zhouling', 'China');
insert into CITIES (id, name, country) values (37, 'Keruguya', 'Kenya');
insert into CITIES (id, name, country) values (38, 'Zhonghualu', 'China');
insert into CITIES (id, name, country) values (39, 'Derhachi', 'Ukraine');
insert into CITIES (id, name, country) values (40, 'Antas', 'Portugal');
insert into CITIES (id, name, country) values (41, 'Kommunar', 'Russia');
insert into CITIES (id, name, country) values (42, 'Jardim', 'Brazil');
insert into CITIES (id, name, country) values (43, 'Sypniewo', 'Poland');
insert into CITIES (id, name, country) values (44, 'Yongyang', 'China');
insert into CITIES (id, name, country) values (45, 'Bahay Pare', 'Philippines');
insert into CITIES (id, name, country) values (46, 'Bulan', 'Philippines');
insert into CITIES (id, name, country) values (47, 'Příšovice', 'Czech Republic');
insert into CITIES (id, name, country) values (48, 'Khandagayty', 'Russia');
insert into CITIES (id, name, country) values (49, 'Henglu', 'China');
insert into CITIES (id, name, country) values (50, 'Ijuí', 'Brazil');
insert into CITIES (id, name, country) values (51, 'Catia La Mar', 'Venezuela');
insert into CITIES (id, name, country) values (52, 'Agoncillo', 'Philippines');
insert into CITIES (id, name, country) values (53, 'Cocobeach', 'Gabon');
insert into CITIES (id, name, country) values (54, 'Mircze', 'Poland');
insert into CITIES (id, name, country) values (55, 'Buôn Ma Thuột', 'Vietnam');
insert into CITIES (id, name, country) values (56, 'Datar', 'Indonesia');
insert into CITIES (id, name, country) values (57, 'Talawakele', 'Sri Lanka');
insert into CITIES (id, name, country) values (58, 'Xingxi', 'China');
insert into CITIES (id, name, country) values (59, 'Langqi', 'China');
insert into CITIES (id, name, country) values (60, 'Pawitan', 'Indonesia');
insert into CITIES (id, name, country) values (61, 'Banyue', 'China');
insert into CITIES (id, name, country) values (62, 'Täby', 'Sweden');
insert into CITIES (id, name, country) values (63, 'Paitan Norte', 'Philippines');
insert into CITIES (id, name, country) values (64, 'Ladysmith', 'Canada');
insert into CITIES (id, name, country) values (65, 'La Huerta', 'Mexico');
insert into CITIES (id, name, country) values (66, 'Duraykīsh', 'Syria');
insert into CITIES (id, name, country) values (67, 'Haodi', 'China');
insert into CITIES (id, name, country) values (68, 'Herong', 'China');
insert into CITIES (id, name, country) values (69, 'Kaduheuleut', 'Indonesia');
insert into CITIES (id, name, country) values (70, 'Xianghu', 'China');
insert into CITIES (id, name, country) values (71, 'Sarykemer', 'Kazakhstan');
insert into CITIES (id, name, country) values (72, 'Bacnor East', 'Philippines');
insert into CITIES (id, name, country) values (73, 'Sukojember', 'Indonesia');
insert into CITIES (id, name, country) values (74, 'Caramay', 'Philippines');
insert into CITIES (id, name, country) values (75, 'Jalaud', 'Philippines');
insert into CITIES (id, name, country) values (76, 'München', 'Germany');
insert into CITIES (id, name, country) values (77, 'Marseille', 'France');
insert into CITIES (id, name, country) values (78, 'Qinghe', 'China');
insert into CITIES (id, name, country) values (79, 'Pagedangan', 'Indonesia');
insert into CITIES (id, name, country) values (80, 'San José de Mayo', 'Uruguay');
insert into CITIES (id, name, country) values (81, 'Yongfa', 'China');
insert into CITIES (id, name, country) values (82, 'Hefei', 'China');
insert into CITIES (id, name, country) values (83, 'Kemlya', 'Russia');
insert into CITIES (id, name, country) values (84, 'Phoenix', 'United States');
insert into CITIES (id, name, country) values (85, 'Hostos', 'Dominican Republic');
insert into CITIES (id, name, country) values (86, 'Sunduk', 'Indonesia');
insert into CITIES (id, name, country) values (87, 'Soio', 'Angola');
insert into CITIES (id, name, country) values (88, 'Pokrov', 'Russia');
insert into CITIES (id, name, country) values (89, 'Qorovulbozor Shahri', 'Uzbekistan');
insert into CITIES (id, name, country) values (90, 'Pak Kret', 'Thailand');
insert into CITIES (id, name, country) values (91, 'Bamencheng', 'China');
insert into CITIES (id, name, country) values (92, 'Outjo', 'Namibia');
insert into CITIES (id, name, country) values (93, 'Santa Cruz', 'Philippines');
insert into CITIES (id, name, country) values (94, 'Wādī Raḩḩāl', 'Palestinian Territory');
insert into CITIES (id, name, country) values (95, 'Sidowayah Lor', 'Indonesia');
insert into CITIES (id, name, country) values (96, 'Cimahi', 'Indonesia');
insert into CITIES (id, name, country) values (97, 'Surkhet', 'Nepal');
insert into CITIES (id, name, country) values (98, 'Yurovka', 'Russia');
insert into CITIES (id, name, country) values (99, 'Öjebyn', 'Sweden');
insert into CITIES (id, name, country) values (100, 'Neepawa', 'Canada');
